version: "3"
services:
  php:
    container_name: hotspot-php
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ./apache_conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
